### ISSUE TITLE
Rebalances for Z0

### ISSUE THREAD

**Issue by Blaylock1988** [GV-Kharak/GVK-Settings#192]
- [x] Allow upgrades in Z2
- [x] Disable Upgraded and Advanced Static Drills in Z0
- [x] Add mild perks to Territories
- [x] Increase cost of MAC tech

**Comment by keleios** [comment]
My thoughts on the list:

- Keep MnM in Z0 as it is the mechanism people use to build grids to venture out into higher order zones.
- Agree
- Maybe disable Tier 2 and 3 drills in Z0 but not the Basic Tier 1 static drill.
- I think perks for territories is less valuable than having better resources at or near territory, particularly ice. They can be outside the bubble. Most factions base on Ice for a reason. Drill outposts are kinda trash having built half a dozen at this point. They always get wacked by Cargo Ships or drones or whatever.
- MAC does seem strong, particularly with limits on maneuverability and the how impractical light armor fliers are in a drone filled environment when one can spawn in range of you at any time.
